name: helpstudent
description: "An app to help students."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  flutter_svg: ^1.1.6
  geolocator: ^9.0.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.5
  url_launcher: ^6.3.1
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  pdf: ^3.11.3
  open_file: ^3.5.10
  location: ^5.0.3
  google_maps_flutter: ^2.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/icons8-parking-48.png
    - assets/img/icons8-university-48.png
    - assets/img/icons8-hospital-50.png
    - assets/img/icons8-mosque-48.png
    - assets/img/icons8-tree-48.png
    - assets/img/icons8-sea-waves-48.png
    - assets/img/icons8-bank-building-48.png
    - assets/img/icons8-insert-credit-card-40.png
    - assets/img/icons8-photo-48.png
    - assets/img/icons8-coffee-48.png
    - assets/img/icons8-graduation-64.png
    - assets/img/icons8-helicopter-48.png
    - assets/img/icons8-stadium-40.png
    - assets/img/icons8-university-60.png
    - assets/img/icons8-library-50.png
    - assets/img/icons8-bus-67.png
    - assets/img/icons8-sleeping-in-bed-50.png
    - assets/img/icons8-classroom-48.png
    - assets/img/icons8-sleeping-in-bed-50.png