name: helpstudent
description: "An app to help students."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4

  flutter_svg: ^1.1.6
  geolocator: ^9.0.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  url_launcher: ^6.3.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  firebase_database: ^11.3.6
  google_maps_flutter: ^2.6.0
  location: ^8.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - img/icons8-parking-48.png
    - img/icons8-classroom-50.png
    - img/icons8-stadium-40.png
    - img/icons8-student-center-48.png